"""Add unique constraint on user_lab_role

Revision ID: 22c88e0116ad
Revises: f8a719fb9c5a
Create Date: 2025-10-14 19:53:55.519712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c88e0116ad'
down_revision = 'f8a719fb9c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lab_role', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_lab', ['user_id', 'lab_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lab_role', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_lab', type_='unique')

    # ### end Alembic commands ###
