"""Add relationships between models

Revision ID: 2856772b6247
Revises: 0daaeb042842
Create Date: 2025-10-14 16:12:13.195783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2856772b6247'
down_revision = '0daaeb042842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cycle_provider_id', 'provider', ['provider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cycle_provider_id', type_='foreignkey')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###
