"""Add missing foreign keys

Revision ID: 4bc03b77ff77
Revises: 2856772b6247
Create Date: 2025-10-14 16:20:09.283784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc03b77ff77'
down_revision = '2856772b6247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_doc', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cycle_doc_cycle_code', 'cycle', ['cycle_code'], ['code'])

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_participation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_result_lab_participation_id', 'lab_participation', ['lab_participation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint('fk_result_lab_participation_id', type_='foreignkey')
        batch_op.drop_column('lab_participation_id')

    with op.batch_alter_table('cycle_doc', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cycle_doc_cycle_code', type_='foreignkey')

    # ### end Alembic commands ###
