"""add xpt_robust sigma_pt_robust to cycle_parameter

Revision ID: 631dd1118945
Revises: 22c88e0116ad
Create Date: 2026-03-16 15:00:12.519031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631dd1118945'
down_revision = '22c88e0116ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_parameter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xpt_robust', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('sigma_pt_robust', sa.Numeric(precision=18, scale=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_parameter', schema=None) as batch_op:
        batch_op.drop_column('sigma_pt_robust')
        batch_op.drop_column('xpt_robust')

    # ### end Alembic commands ###
