"""Add registration and invite models

Revision ID: cf05f5b04658
Revises: 9056ee198d10
Create Date: 2025-10-14 17:44:42.704647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf05f5b04658'
down_revision = '9056ee198d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_code', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=96), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_token_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_token_lab_code'), ['lab_code'], unique=False)

    op.create_table('registration_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('desired_lab_name', sa.String(length=100), nullable=True),
    sa.Column('target_lab_code', sa.String(length=20), nullable=True),
    sa.Column('desired_role', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_request_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_request_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_request_status'))
        batch_op.drop_index(batch_op.f('ix_registration_request_email'))

    op.drop_table('registration_request')
    with op.batch_alter_table('invite_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_token_lab_code'))
        batch_op.drop_index(batch_op.f('ix_invite_token_email'))

    op.drop_table('invite_token')
    # ### end Alembic commands ###
